# Use root/example as user/password credentials
version: "3"

services:
    mysql:
        image: mysql:5.7
        container_name: go_boilerplate_db
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: go_boilerplate
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
